Smoke

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -420,35 +420,55 @@ jobs:
       - run:
           name: Backend smoke test.
           command: |
-            # your code here
-            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
-            --filters Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7} \
+            # # your code here
+            # BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+            # --filters Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7} \
+            # --query 'Reservations[*].Instances[*].PublicIpAddress' \
+            # --output text
+            # )
+            # export API_URL="http://${BACKEND_PUBLIC_IP}:3030"
+            # echo ${BACKEND_PUBLIC_IP}
+            # echo backend-${CIRCLE_WORKFLOW_ID:0:7}
+            # echo "${API_URL}"
+            # if curl -s "${API_URL}/api/status" | grep "ok"
+            # then
+            #   exit 1
+            # else
+            #   exit 1
+            # fi
+            export BACKEND_IP=$(aws ec2 describe-instances \
             --query 'Reservations[*].Instances[*].PublicIpAddress' \
-            --output text
-            )
-            export API_URL="http://${BACKEND_PUBLIC_IP}:3030"
-            echo ${BACKEND_PUBLIC_IP}
-            echo backend-${CIRCLE_WORKFLOW_ID:0:7}
+            --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" --output text)
+            export API_URL="http://${BACKEND_IP}:3030"
             echo "${API_URL}"
-            if curl -s "${API_URL}/api/status" | grep "ok"
+            if curl "${API_URL}/api/status" | grep "ok"
             then
-              exit 1
+              return 0
             else
-              exit 1
+              return 1
             fi
       - run:
           name: Frontend smoke test.
           command: |
             # your code here
             
-            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com            
-            echo ${URL} 
-            if curl -s ${URL} | grep "Welcome"
+            # URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com            
+            # echo ${URL} 
+            # if curl -s ${URL} | grep "Welcome"
+            # then
+            # # Change this to 0 after the job fails
+            #   exit 1
+            # else
+            #   exit 1
+            # fi
+            export URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-west-2.amazonaws.com/#/employees"            
+            echo $URL
+            if curl ${URL} | grep "Welcome"
             then
-            # Change this to 0 after the job fails
-              exit 1
+              # Change this to 0 after the job fails
+              return 0
             else
-              exit 1
+              return 1
             fi
       # - destroy-environment
       # - revert-migrations      
